<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Version>1.0.0</Version>
    <PackageTags>excel pdf png closedxml pdfsharp skiasharp</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/akrym1582/ExcelRenderer</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>

  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="PDFsharp" Version="6.2.3" />
    <PackageReference Include="SkiaSharp" Version="4.151.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.0" />
  </ItemGroup>
</Project>
